añadido test de container up (previo a pytest) y añadido cleanup container2

diff --git a/.github/workflows/demo1.yml b/.github/workflows/demo1.yml
--- a/.github/workflows/demo1.yml
+++ b/.github/workflows/demo1.yml
@@ -56,7 +56,7 @@ jobs:
       - name: Build docker image
         run: docker image build -t securityscanservice .
       - name: Run container from image
-        run: docker container run -d -p 8000:8000 securityscanservice
+        run: docker container run --name securityscan -d -p 8000:8000 securityscanservice
       - name: Smoke test (wait & ping / and POST /api/scan)
         run: |
           set -e
@@ -68,19 +68,19 @@ jobs:
               break; 
             fi
             sleep 1
-            [ $i -eq 30 ] && echo "Service not ready" && docker logs securityscanservice && exit 1
+            [ $i -eq 30 ] && echo "Service not ready" && docker logs securityscan && exit 1
           done
           #POST sencillo a /api/scan y comprobar 200
           code=$(curl -s -o /dev/null -w "%{http_code}" \
             -H 'Content-Type: application/json' \
             -d '{"scan_type":"url","target":"scanme.nmap.org"}' \
             http://localhost:8000/api/scan)
-          [ "$code" = "200" ] || {echo "POST /api/scan failed ($code)"; docker logs securityscanservice; exit 1;}
+          [ "$code" = "200" ] || { echo "POST /api/scan failed ($code)"; docker logs securityscan; exit 1; }
       - name: Run pytest 
         run: pytest -q -vv -s
       - name: Stop container
         if: always()
-        run: docker stop securityscanservice
+        run: docker stop securityscan
   deploy:
     runs-on: ubuntu-latest
     needs: build
